// Archivo de datos separado. 
// Lo declaramos como una variable global para evitar problemas de seguridad (CORS) 
// que ocurren al intentar leer archivos .json directamente haciendo doble clic en el HTML.

const productsData = [
    // Infusiones Medicinales
    { id: 1, name: "Infusión Malestar Estomacal", category: "Infusiones", price: 2.00, imagePath: "assets/products/estomago.jpg", description: "¿Comidas pesadas? Recupera tu bienestar al instante. Nuestra tradicional mezcla de plantas digestivas, cultivadas de forma natural, te ayuda a despedirte de la pesadez, los gases y el malestar. Este formato incluye 5 cómodas infusiones monodosis listas para devolverle la sonrisa a tu estómago.", ingredients: "Regaliz, Diente de león, Manzanilla." },
    { id: 2, name: "Infusión Dolor General", category: "Infusiones", price: 2.00, imagePath: "assets/products/dolor.jpg", description: "¿Ese dolor que simplemente no te deja? La ulmaria lleva siglos siendo el remedio natural por excelencia para las molestias musculares, articulares y los dolores de cabeza. Conocida como la 'aspirina de los bosques', actúa con suavidad y sin efectos secundarios. 5 infusiones monodosis de planta pura — tu aliada natural por solo 2€.", ingredients: "Ulmaria." },
    { id: 3, name: "Infusión Dolor de Garganta", category: "Infusiones", price: 2.00, imagePath: "assets/products/garganta.jpg", description: "¿La garganta te raspa y la voz te falla? El erísimo, la planta preferida de cantantes y oradores durante siglos, combinado con el llantén suavizante, te devuelve la voz y el confort en cada sorbo. 5 infusiones monodosis de planta pura — el remedio clásico para los días que más lo necesitas.", ingredients: "Llantén, Erísimo." },
    { id: 4, name: "Infusión Dolor Menstrual", category: "Infusiones", price: 2.00, imagePath: "assets/products/menstrual.jpg", description: "¿Esos días del mes que se hacen cuesta arriba? La milenrama, aliada del ciclo femenino desde la antigüedad, trabaja junto a la cola de caballo para calmar los espasmos, reducir la inflamación y aliviar la pesadez. 5 infusiones monodosis para acompañarte cuando más lo necesitas.", ingredients: "Milenrama, Cola de caballo." },
    { id: 5, name: "Infusión Catarro", category: "Infusiones", price: 2.00, imagePath: "assets/products/catarro.jpg", description: "¿La nariz taponada, el pecho cargado y el cuerpo sin energía? El tomillo despeja y desinfecta, la pulmonaria cuida tus bronquios y el llantén calma la irritación de la mucosa. Una fórmula botánica de toda la vida para ponerte en pie cuanto antes. 5 infusiones monodosis listas para cuando más las necesitas.", ingredients: "Pulmonaria, Llantén, Tomillo." },
    { id: 6, name: "Infusión Para Dormir", category: "Infusiones", price: 2.00, imagePath: "assets/products/dormir.jpg", description: "¿La mente no para y el sueño no llega? La raíz de valeriana y la pasiflora calman el sistema nervioso con suavidad, mientras la hierba luisa añade un toque cítrico que convierte cada sorbo en un ritual de descanso. Sin dependencia, sin química. 5 infusiones monodosis para recuperar tus noches.", ingredients: "Raíz de valeriana, Pasiflora, Hierba luisa." },
    { id: 7, name: "Infusión Detox", category: "Infusiones", price: 2.00, imagePath: "assets/products/detox.jpg", description: "¿Sientes el cuerpo pesado y necesitas un reinicio? El diente de león activa el hígado y los riñones, la ortiga verde mineraliza y purifica, y el llantén calma la mucosa digestiva. Tres plantas, un objetivo: ayudar a tu cuerpo a limpiarse por dentro. 5 infusiones monodosis para empezar de cero.", ingredients: "Diente de León, Ortiga verde, Llantén." },
    { id: 8, name: "Infusión Para la Resaca", category: "Infusiones", price: 2.00, imagePath: "assets/products/resaca.jpg", description: "¿Esa mañana en la que el cuerpo te pasa factura? La ortiga y el diente de león ponen en marcha el hígado y los riñones para eliminar toxinas, mientras el llantén calma y protege el estómago irritado. Sin milagros, pero casi. 5 infusiones monodosis para volver a ser tú.", ingredients: "Ortiga, Diente de León, Llantén." },
    { id: 9, name: "Infusión Limpieza Pulmonar", category: "Infusiones", price: 2.00, imagePath: "assets/products/pulmones.jpg", description: "¿Tos persistente, bronquios cargados o pulmones que no terminan de recuperarse? La drosera es una de las plantas más potentes contra la tos espasmódica, y la pulmonaria lleva siglos cuidando las vías respiratorias bajas. Juntas, una limpieza profunda en cada taza. 5 infusiones monodosis para que vuelvas a respirar con libertad.", ingredients: "Drosera, Pulmonaria." },
    { id: 10, name: "Infusión Mucolítica", category: "Infusiones", price: 2.00, imagePath: "assets/products/mocos.jpg", description: "¿Esa mucosidad que no cede y te tiene agotado? La pulmonaria, fiel aliada de las vías respiratorias desde la medicina tradicional, ayuda a fluidificar y expulsar el exceso de moco de forma natural y suave. Sin aditivos, planta pura. 5 infusiones monodosis para que puedas respirar — y vivir — con normalidad.", ingredients: "Pulmonaria." },

    // Aceites de Maceración
    { id: 11, name: "Aceite de Hipérico", category: "Aceites", price: 8.00, imagePath: "assets/products/aceitehiperico.jpg", description: "El rojo intenso de este aceite lo dice todo: meses de maceración solar del hipérico en aceite de girasol puro. Un clásico de la herboristería tradicional para masajes en zonas con tensión muscular, golpes y pequeñas molestias articulares. Botella de 100 ml. ⚠️ Fototóxico — no exponer la zona tratada al sol.", ingredients: "Aceite de girasol, Hipérico." },
    { id: 12, name: "Aceite de Lavanda", category: "Aceites", price: 8.00, imagePath: "assets/products/aceitelavanda.jpg", description: "¿Piel tirante o un día cargado de tensión? Nuestro macerado artesanal de flores de lavanda en aceite de girasol puro calma la piel, alivia pequeñas irritaciones y aquieta la mente gracias a su aroma suave y natural. El toque perfecto para masajes relajantes antes de dormir. Botella de 100 ml.", ingredients: "Aceite de girasol, Lavanda." },
    { id: 13, name: "Aceite de Caléndula", category: "Aceites", price: 8.00, imagePath: "assets/products/aceitecalendula.jpg", description: "¿Piel sensible, irritada o especialmente seca? La caléndula es el mimo botánico definitivo. Macerada en aceite de girasol, nutre en profundidad, calma rojeces y repara la barrera cutánea con total delicadeza. El aliado imprescindible para toda la familia. Botella de 100 ml.", ingredients: "Aceite de girasol, Caléndula." },
    { id: 14, name: "Aceite de Romero", category: "Aceites", price: 8.00, imagePath: "assets/products/aceiteromero.jpg", description: "¿Músculos cargados tras un largo día o esfuerzo físico? La maceración de romero silvestre en aceite de girasol activa la circulación, reconforta articulaciones y alivia la fatiga corporal con su frescor vigorizante. El imprescindible para masajes de recuperación y vitalidad. Botella de 100 ml.", ingredients: "Aceite de girasol, Romero." },

    // Cosmética e Higiene
    { id: 15, name: "Jabón Artesanal (Oliva y Coco)", category: "Higiene", price: 3.00, imagePath: "assets/products/jabones.png", description: "¿Cansado de geles y jabones comerciales que dejan tu piel tirante y seca? Elaborado de forma artesanal mediante saponificación tradicional en frío, este jabón combina la nutrición profunda del aceite de oliva virgen con la espuma suave y cremosa del coco. Limpieza pura, hidratación duradera y cero químicos sintéticos. Venta a peso: corte fresco de 100 g por solo 3€.", ingredients: "Aceite de oliva virgen extra, Aceite de coco, Agua, Hidróxido de sodio." },
];
